=== styltsars96/DB2016-17/2/XML results after cleanup/players.dtd
<!DOCTYPE nba>
<!ELEMENT nba (division*)>
<!ATTLIST nba dataset CDATA #REQUIRED>
<!ELEMENT division (player*)>
<!ATTLIST division id CDATA #REQUIRED>
<!ELEMENT player (playerid,firstname,lastname,position,points,minutes,index?,tendex?,teamname,teamid)>
<!ELEMENT playerid (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT points (#PCDATA)>
<!ELEMENT minutes (#PCDATA)>
<!ELEMENT index (#PCDATA)>
<!ELEMENT tendex (#PCDATA)>
<!ELEMENT teamname (#PCDATA)>
<!ELEMENT teamid (#PCDATA)>

=== styltsars96/DB2016-17/2/XML results after cleanup/topplayers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nba SYSTEM "players.dtd">
<nba dataset="topplayers">
<division id="East"><player><playerid>jamesle01</playerid><firstname>LeBron</firstname><lastname>James</lastname><position>F</position><points>2258</points><minutes>2966</minutes><index>0</index><tendex>0.821</tendex><teamname>Cleveland Cavaliers</teamname><teamid>CLE</teamid></player><player><playerid>davispa01</playerid><firstname>Paul</firstname><lastname>Davis</lastname><position>C</position><points>5</points><minutes>8</minutes><index>1</index><tendex>0.8125</tendex><teamname>Washington Wizards</teamname><teamid>WAS</teamid></player><player><playerid>howardw01</playerid><firstname>Dwight</firstname><lastname>Howard</lastname><position>F</position><points>1503</points><minutes>2843</minutes><index>2</index><tendex>0.6966</tendex><teamname>Orlando Magic</teamname><teamid>ORL</teamid></player><player><playerid>boshch01</playerid><firstname>Christopher</firstname><lastname>Bosh</lastname><position>F</position><points>1678</points><minutes>2526</minutes><index>3</index><tendex>0.6956</tendex><teamname>Toronto Raptors</teamname><teamid>TOR</teamid></player><player><playerid>wadedw01</playerid><firstname>Dwyane</firstname><lastname>Wade</lastname><position>G</position><points>2045</points><minutes>2792</minutes><index>4</index><tendex>0.6569</tendex><teamname>Miami Heat</teamname><teamid>MIA</teamid></player><player><playerid>leeda02</playerid><firstname>David</firstname><lastname>Lee</lastname><position>F</position><points>1640</points><minutes>3019</minutes><index>5</index><tendex>0.6492</tendex><teamname>New York Knicks</teamname><teamid>NYK</teamid></player><player><playerid>bogutan01</playerid><firstname>Andrew</firstname><lastname>Bogut</lastname><position>C</position><points>1095</points><minutes>2229</minutes><index>6</index><tendex>0.5846</tendex><teamname>Milwaukee Bucks</teamname><teamid>MIL</teamid></player><player><playerid>murphtr01</playerid><firstname>Troy</firstname><lastname>Murphy</lastname><position>F</position><points>1050</points><minutes>2344</minutes><index>7</index><tendex>0.5629</tendex><teamname>Indiana Pacers</teamname><teamid>IND</teamid></player><player><playerid>smithjo03</playerid><firstname>Joshua</firstname><lastname>Smith</lastname><position>F</position><points>1269</points><minutes>2871</minutes><index>8</index><tendex>0.5592</tendex><teamname>Atlanta Hawks</teamname><teamid>ATL</teamid></player><player><playerid>garneke01</playerid><firstname>Kevin</firstname><lastname>Garnett</lastname><position>F</position><points>990</points><minutes>2060</minutes><index>9</index><tendex>0.5568</tendex><teamname>Boston Celtics</teamname><teamid>BOS</teamid></player><player><playerid>noahjo01</playerid><firstname>Joakim</firstname><lastname>Noah</lastname><position>F-C</position><points>687</points><minutes>1925</minutes><index>10</index><tendex>0.5481</tendex><teamname>Chicago Bulls</teamname><teamid>CHI</teamid></player><player><playerid>horfoal01</playerid><firstname>Alfred</firstname><lastname>Horford Reynoso</lastname><position>F-C</position><points>1148</points><minutes>2845</minutes><index>11</index><tendex>0.538</tendex><teamname>Atlanta Hawks</teamname><teamid>ATL</teamid></player></division>
<division id="West"><player><playerid>gildetr01</playerid><firstname>Trey</firstname><lastname>Gilder</lastname><position>F</position><points>2</points><minutes>5</minutes><index>0</index><tendex>0.8</tendex><teamname>Memphis Grizzlies</teamname><teamid>MEM</teamid></player><player><playerid>duncati01</playerid><firstname>Timothy</firstname><lastname>Duncan</lastname><position>C-F</position><points>1395</points><minutes>2438</minutes><index>1</index><tendex>0.7082</tendex><teamname>San Antonio Spurs</teamname><teamid>SAS</teamid></player><player><playerid>duranke01</playerid><firstname>Kevin</firstname><lastname>Durant</lastname><position>F</position><points>2472</points><minutes>3239</minutes><index>2</index><tendex>0.6681</tendex><teamname>Oklahoma City Thunder</teamname><teamid>OKC</teamid></player><player><playerid>boozeca01</playerid><firstname>Carlos</firstname><lastname>Boozer</lastname><position>F-C</position><points>1519</points><minutes>2673</minutes><index>3</index><tendex>0.6538</tendex><teamname>Utah Jazz</teamname><teamid>UTA</teamid></player><player><playerid>gasolpa01</playerid><firstname>Pau</firstname><lastname>Gasol Saez</lastname><position>F</position><points>1190</points><minutes>2403</minutes><index>4</index><tendex>0.6521</tendex><teamname>Los Angeles Lakers</teamname><teamid>LAL</teamid></player><player><playerid>bowenry01</playerid><firstname>Ryan</firstname><lastname>Bowen</lastname><position>F</position><points>4</points><minutes>8</minutes><index>5</index><tendex>0.625</tendex><teamname>Oklahoma City Thunder</teamname><teamid>OKC</teamid></player><player><playerid>loveke01</playerid><firstname>Kevin</firstname><lastname>Love</lastname><position>F</position><points>842</points><minutes>1714</minutes><index>6</index><tendex>0.6234</tendex><teamname>Minnesota Timberwolves</teamname><teamid>MIN</teamid></player><player><playerid>nashst01</playerid><firstname>Stephen</firstname><lastname>Nash</lastname><position>G</position><points>1333</points><minutes>2660</minutes><index>7</index><tendex>0.6207</tendex><teamname>Phoenix Suns</teamname><teamid>PHO</teamid></player><player><playerid>whitedj01</playerid><firstname>DeWayne</firstname><lastname>White</lastname><position>F</position><points>59</points><minutes>102</minutes><index>8</index><tendex>0.6127</tendex><teamname>Oklahoma City Thunder</teamname><teamid>OKC</teamid></player><player><playerid>paulch01</playerid><firstname>Christopher</firstname><lastname>Paul</lastname><position>G</position><points>841</points><minutes>1712</minutes><index>9</index><tendex>0.6124</tendex><teamname>New Orleans Hornets</teamname><teamid>NOH</teamid></player><player><playerid>nowitdi01</playerid><firstname>Dirk</firstname><lastname>Nowitzki</lastname><position>C</position><points>2027</points><minutes>3039</minutes><index>10</index><tendex>0.6107</tendex><teamname>Dallas Mavericks</teamname><teamid>DAL</teamid></player><player><playerid>stoudam01</playerid><firstname>Amar&apos;e</firstname><lastname>Stoudemire</lastname><position>F-C</position><points>1896</points><minutes>2838</minutes><index>11</index><tendex>0.6055</tendex><teamname>Phoenix Suns</teamname><teamid>PHO</teamid></player></division>
</nba>

=== styltsars96/DB2016-17/2/XML results after cleanup/allstars.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nba SYSTEM "players.dtd">
<nba dataset="allstars">
<division id="East"><player><playerid>leeda02</playerid><firstname>David</firstname><lastname>Lee</lastname><position>F</position><points>4</points><minutes>12</minutes><teamname>New York Knicks</teamname><teamid>NYK</teamid></player><player><playerid>boshch01</playerid><firstname>Christopher</firstname><lastname>Bosh</lastname><position>F</position><points>23</points><minutes>29</minutes><teamname>Toronto Raptors</teamname><teamid>TOR</teamid></player><player><playerid>rosede01</playerid><firstname>Derrick</firstname><lastname>Rose</lastname><position>G</position><points>8</points><minutes>15</minutes><teamname>Chicago Bulls</teamname><teamid>CHI</teamid></player><player><playerid>wadedw01</playerid><firstname>Dwyane</firstname><lastname>Wade</lastname><position>G</position><points>28</points><minutes>31</minutes><teamname>Miami Heat</teamname><teamid>MIA</teamid></player><player><playerid>duncati01</playerid><firstname>Timothy</firstname><lastname>Duncan</lastname><position>C-F</position><points>3</points><minutes>13</minutes><teamname>San Antonio Spurs</teamname><teamid>SAS</teamid></player><player><playerid>garneke01</playerid><firstname>Kevin</firstname><lastname>Garnett</lastname><position>F</position><points>4</points><minutes>13</minutes><teamname>Boston Celtics</teamname><teamid>BOS</teamid></player><player><playerid>horfoal01</playerid><firstname>Alfred</firstname><lastname>Horford Reynoso</lastname><position>F-C</position><points>8</points><minutes>14</minutes><teamname>Atlanta Hawks</teamname><teamid>ATL</teamid></player><player><playerid>howardw01</playerid><firstname>Dwight</firstname><lastname>Howard</lastname><position>F</position><points>17</points><minutes>27</minutes><teamname>Orlando Magic</teamname><teamid>ORL</teamid></player><player><playerid>jamesle01</playerid><firstname>LeBron</firstname><lastname>James</lastname><position>F</position><points>25</points><minutes>32</minutes><teamname>Cleveland Cavaliers</teamname><teamid>CLE</teamid></player><player><playerid>johnsjo02</playerid><firstname>Joe</firstname><lastname>Johnson</lastname><position>G-F</position><points>10</points><minutes>18</minutes><teamname>Atlanta Hawks</teamname><teamid>ATL</teamid></player><player><playerid>piercpa01</playerid><firstname>Paul</firstname><lastname>Pierce</lastname><position>F</position><points>8</points><minutes>11</minutes><teamname>Boston Celtics</teamname><teamid>BOS</teamid></player><player><playerid>rondora01</playerid><firstname>Rajon</firstname><lastname>Rondo</lastname><position>F</position><points>4</points><minutes>20</minutes><teamname>Boston Celtics</teamname><teamid>BOS</teamid></player><player><playerid>wallage01</playerid><firstname>Gerald</firstname><lastname>Wallace</lastname><position>F</position><points>2</points><minutes>16</minutes><teamname>Charlotte Bobcats</teamname><teamid>CHA</teamid></player></division>
<division id="West"><player><playerid>kiddja01</playerid><firstname>Jason</firstname><lastname>Kidd</lastname><position>G</position><points>0</points><minutes>6</minutes><teamname>Dallas Mavericks</teamname><teamid>DAL</teamid></player><player><playerid>nashst01</playerid><firstname>Stephen</firstname><lastname>Nash</lastname><position>G</position><points>4</points><minutes>20</minutes><teamname>Phoenix Suns</teamname><teamid>PHO</teamid></player><player><playerid>anthoca01</playerid><firstname>Carmelo</firstname><lastname>Anthony</lastname><position>F</position><points>27</points><minutes>29</minutes><teamname>Denver Nuggets</teamname><teamid>DEN</teamid></player><player><playerid>billuch01</playerid><firstname>Chauncey</firstname><lastname>Billups</lastname><position>G</position><points>17</points><minutes>26</minutes><teamname>Denver Nuggets</teamname><teamid>DEN</teamid></player><player><playerid>duncati01</playerid><firstname>Timothy</firstname><lastname>Duncan</lastname><position>C-F</position><points>3</points><minutes>13</minutes><teamname>San Antonio Spurs</teamname><teamid>SAS</teamid></player><player><playerid>duranke01</playerid><firstname>Kevin</firstname><lastname>Durant</lastname><position>F</position><points>15</points><minutes>20</minutes><teamname>Oklahoma City Thunder</teamname><teamid>OKC</teamid></player><player><playerid>gasolpa01</playerid><firstname>Pau</firstname><lastname>Gasol Saez</lastname><position>F</position><points>13</points><minutes>20</minutes><teamname>Los Angeles Lakers</teamname><teamid>LAL</teamid></player><player><playerid>kamanch01</playerid><firstname>Christopher</firstname><lastname>Kaman</lastname><position>C</position><points>4</points><minutes>11</minutes><teamname>Los Angeles Clippers</teamname><teamid>LAC</teamid></player><player><playerid>nowitdi01</playerid><firstname>Dirk</firstname><lastname>Nowitzki</lastname><position>C</position><points>22</points><minutes>28</minutes><teamname>Dallas Mavericks</teamname><teamid>DAL</teamid></player><player><playerid>randoza01</playerid><firstname>Zachary</firstname><lastname>Randolph</lastname><position>F</position><points>8</points><minutes>19</minutes><teamname>Memphis Grizzlies</teamname><teamid>MEM</teamid></player><player><playerid>stoudam01</playerid><firstname>Amar&apos;e</firstname><lastname>Stoudemire</lastname><position>F-C</position><points>12</points><minutes>20</minutes><teamname>Phoenix Suns</teamname><teamid>PHO</teamid></player><player><playerid>willide01</playerid><firstname>Deron</firstname><lastname>Williams</lastname><position>G</position><points>14</points><minutes>28</minutes><teamname>Utah Jazz</teamname><teamid>UTA</teamid></player></division>
</nba>
